import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-tertiary": "var(--color-text-tertiary)",
        "text-quaternary": "var(--color-text-quaternary)",
        "brand-foreground": "var(--color-brand-foreground)",
        "background-base": "var(--color-background-base)",
        "background-primary-container": "var(--color-background-primary-container)",
        "background-components": "var(--color-background-components)",
        "background-popup-components": "var(--color-background-popup-components)",
        "background-mask": "var(--color-background-mask)",
        "background-table-zebra-striping": "var(--color-background-table-zebra-striping)",
        "border-solid-line-1": "var(--color-border-solid-line-1)",
        "border-solid-line-2": "var(--color-border-solid-line-2)",
        "border-components-line": "var(--color-border-components-line)",
        "border-container-line": "var(--color-border-container-line)",
        "gray-transparent": "var(--color-gray-transparent)",
        "gray-stroke": "var(--color-gray-stroke)",
        "gray-1": "var(--color-gray-1)",
        "gray-2": "var(--color-gray-2)",
        "gray-3": "var(--color-gray-3)",
        "gray-4": "var(--color-gray-4)",
        "gray-5": "var(--color-gray-5)",
        "gray-6": "var(--color-gray-6)",
        "gray-7": "var(--color-gray-7)",
        "gray-8": "var(--color-gray-8)",
        "gray-9": "var(--color-gray-9)",
        "gray-10": "var(--color-gray-10)",
        "functional-brand-foreground": "var(--color-functional-brand-foreground)",
        "functional-brand-background": "var(--color-functional-brand-background)",
        "functional-brand-transparent": "var(--color-functional-brand-transparent)",
        "functional-brand-foreground-solid": "var(--color-functional-brand-foreground-solid)",
        "functional-blue-foreground": "var(--color-functional-blue-foreground)",
        "functional-blue-background": "var(--color-functional-blue-background)",
        "functional-blue-transparent": "var(--color-functional-blue-transparent)",
        "functional-success-foreground": "var(--color-functional-success-foreground)",
        "functional-success-background": "var(--color-functional-success-background)",
        "functional-success-transparent": "var(--color-functional-success-transparent)",
        "functional-yellow-foreground": "var(--color-functional-yellow-foreground)",
        "functional-yellow-background": "var(--color-functional-yellow-background)",
        "functional-yellow-transparent": "var(--color-functional-yellow-transparent)",
        "functional-warning-foreground": "var(--color-functional-warning-foreground)",
        "functional-warning-background": "var(--color-functional-warning-background)",
        "functional-warning-transparent": "var(--color-functional-warning-transparent)",
        "functional-error-foreground": "var(--color-functional-error-foreground)",
        "functional-error-background": "var(--color-functional-error-background)",
        "functional-error-transparent": "var(--color-functional-error-transparent)",
        "background-primary-container--active": "var(--color-background-primary-container--active)",
        "background-components--active": "var(--color-background-components--active)",
        "gray-2--active": "var(--color-gray-2--active)",
        "gray-5--active": "var(--color-gray-5--active)",
        "gray-8--active": "var(--color-gray-8--active)",
        "functional-error-background--active": "var(--color-functional-error-background--active)",
        "functional-brand-background--active": "var(--color-functional-brand-background--active)",
        "functional-error-transparent--active": "var(--color-functional-error-transparent--active)",
      },
      boxShadow: {
        card: "0 1px 2px rgb(0 0 0 / 0.08), 0 8px 24px rgb(0 0 0 / 0.16)",
        lift: "0 8px 20px rgb(0 0 0 / 0.28)",
      },
    },
  },
  plugins: [],
} satisfies Config;
